[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "easyorg"
version = "1.0.0"
description = "Organizador seguro de fotos y videos por fecha"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "MiguelIGP23" }]

[project.scripts]
easyorg = "easyorg.cli.app:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
