[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "easyorg"
version = "0.1.0"
description = "Organizador seguro de fotos y videos por fecha"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "MiguelIGP23" }]

[tool.pytest.ini_options]
testpaths = ["tests"]
